### ISSUE TITLE
Obsolete references

### ISSUE THREAD

**Issue by MarcJamesIO** [Cyanilux/URP_WatercolourShaders#4]
Thanks, the project looks really cool but unfortunately doesn't work in Unity 6 due to obsolete references regarding the Blit functions.

**Comment by Cyanilux** [comment]
No plans to update the repo, but for 2022+ you'd likely use the Fullscreen Graph and Fullscreen Pass Renderer Feature provided by URP
URP also now has Decal Graphs (& Decal Renderer Feature) to replace the "reconstruct from depth" method used to create the splodge decals
